<?php

/**
 * Commit
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package sfjp
 * @subpackage model
 * @author hidenorigoto
 * @version SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Commit extends BaseCommit {
    const GRAVATAR_URL = 'http://www.gravatar.com/avatar/';

    /**
     * Commit::getCommitterGravatarUrl()
     * コミッターのメールアドレスに対応するGRAVATAR画像のURLを生成する。
     *
     * @param 　integer $size 省略した場合は24
     * @return string　　画像URL
     */
    public function getCommitterGravatarUrl($size = 24)
    {
        $url = sprintf('%s%s',
                self::GRAVATAR_URL,
                md5($this->getCommitterEmail())
               );
        if (1 <= $size && 512 >= $size) {
            $url .= sprintf('?s=%s', $size);
        }

        return $url;
    }

    /**
     * Commit::postSave()
     * レコード保存時のフック
     *
     * @param mixed $event
     * @return
     */
    public function postSave($event)
    {
        $page = $this->getPage();

        // 関連するページの最終更新日、初回コミット日を更新する。
        $page->updateLastUpdated();
        $page->updateFirstCommitted();
    }
}