homepage:
  url:   /
  param: { module: top, action: index }

feed:
  url:   /feed
  param: { module: feed, action: index }


blog_list:
  url:   /blog/
  param: { module: blog, action: index }


repository:
  class: sfDoctrineRouteCollection
  options:
    model:                Repository
    module:               admin
    prefix_path:          /admin
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /admin/login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /admin/logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /admin/request_password
  param: { module: sfGuardAuth, action: password }

admin:
  url:   /admin/
  param:  { module: admin, action: index }

default:
  url:   /*
  param: { module: page, action: page }
