homepage:
  url:   /
  param: { module: top, action: index }

feed:
  url:   /feed
  param: { module: feed, action: index }

repository:
  class: sfDoctrineRouteCollection
  options:
    model:                Repository
    module:               admin
    prefix_path:          /admin
    column:               id
    with_wildcard_routes: true

#page3a:
#  url:   /:key1/:key2/:key3/
#  param: { module: page, action: page_index }
#page3:
#  url:   /:key1/:key2/:key3
#  param: { module: page, action: page }
#
#
#page2a:
#  url:   /:key1/:key2/
#  param: { module: page, action: page_index }
#page2:
#  url:   /:key1/:key2
#  param: { module: page, action: page }
#
#
#page1a:
#  url:   /:key1/
#  param: { module: page, action: page_index }
#page1:
#  url:   /:key1
#  param: { module: page, action: page }

sf_guard_signin:
  url:   /admin/login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /admin/logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /admin/request_password
  param: { module: sfGuardAuth, action: password }

admin:
  url:   /admin/
  param:  { module: admin, action: index }

default:
  url:   /*
  param: { module: page, action: page }
