<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('page', 'IX_Page_1', array(
             'fields' => 
             array(
              0 => 'path',
             ),
             ));
        $this->addIndex('page', 'IX_Page_2', array(
             'fields' => 
             array(
              0 => 'path',
              1 => 'last_updated_ym',
             ),
             ));
    }

    public function down()
    {
        $this->addIndex('page', 'IX_Page_1', array(
             'fields' => 
             array(
              0 => 'path',
             ),
             ));
        $this->removeIndex('page', 'IX_Page_2', array(
             'fields' => 
             array(
              0 => 'path',
              1 => 'last_updated_ym',
             ),
             ));
    }
}