<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addrepository extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('repository', array(
             'id' => 
             array(
              'primary' => true,
              'unsigned' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'repository' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 256,
             ),
             'subdirectory' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'bind_path' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 128,
             ),
             'settings_json' => 
             array(
              'type' => 'string',
              'length' => 512,
             ),
             'force_update' => 
             array(
              'default' => 0,
              'type' => 'boolean',
              'length' => 25,
             ),
             'force_clone' => 
             array(
              'default' => 0,
              'type' => 'boolean',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('repository');
    }
}