<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('page', 'last_updated_ym', 'integer', '8', array(
             'default' => '0',
             ));
        $this->addColumn('page', 'first_committed', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('page', 'last_updated_ym');
        $this->removeColumn('page', 'first_committed');
    }
}